# -*- coding: utf-8 -*-
"""friends_gplus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JkDvKxVczq7wfPNw22ACNdUHhZkP1a4A
"""

# montar a drive e imports
import pandas as pd
import time
import random

from google.colab import drive
drive.mount('/content/drive')

# source http://snap.stanford.edu/data/ego-Facebook.html
# File path
filepath = '/content/drive/MyDrive/Colab Notebooks/Computação na Cloud (CC)/gplus_combined.csv'
# pandas to read dataset
dataset = pd.read_csv(filepath, delimiter=' ')
print("Dataset\n", dataset)

x = dataset.iloc[:, 0]
y = dataset.iloc[:, 1]

# Ids to search friends
# Change this value to get the number of IDs to find the mutual friends
n_ids = 3
friend = []
count = []

for i in range(n_ids):
  friend.append(x[random.randint(0, 30494865)])
  count.append(0)

'''
# Exemples for debugging:
# 2 IDs
109123727761757726835
100722679426961808186
_____________________
2356 mutual friends

# 3 IDs
103652441454188509895
116635061583722144944
113882113745075873153
______________________
1405 mutual friends

'''

t0 = time.time()

# Counting nº of friends to each ID
# Each line is: friend0 friend_0
#               friend0 friend_1
#               friend0 friend_2

# Computational Complexity: O(n^m)
for i in x:
  for j in range(len(friend)):
    if friend[j] == i:
      count[j] += 1
t1 = time.time()

print('Delta t(s) = ', (t1-t0))
for i in range(len(friend)):
  print('Nº of friends of %s: %d' %(friend[i], count[i]))

# Now counts the number of mutual friends
# Computational Complexity: O(n + n*m)
# Mutual Friends will be
mutual_friends = []
friends_in_common = 0
t0 = time.time()

# Fetch the friends of each and appends them to a list
for i in range(len(x)):
  for j in friend:
    if j == x[i]:
      s = y[i] + '\t1'
      mutual_friends.append(s)
  
t1 = time.time()

# Now we sort the list (matches the MapReduce Job on Hadoop)
mutual_friends.sort()

# verify if there is any mutual friend
line = mutual_friends[0]
current_id, current_count = line.split('\t', 1)
current_count = int(current_count)
for i in range(1, len(mutual_friends)):
  line = mutual_friends[i]
  id, count = line.split('\t', 1)
  count = int(count)
  if current_id == id:
    current_count += 1
    if current_count == n_ids:
      friends_in_common += 1
  else:
    current_count = count
    current_id = id
  

t2 = time.time()

print('Delta fetch friends(s) = %.2f' %(t1-t0))
print('Delta mutual friends(s) = %.2f' %(t2-t1))
print('Delta Total(s) = %.2f' %(t2-t0))
print('Nº of mutual friends: ', friends_in_common)
